---
- name: Install helm
  community.general.snap:
    name: helm
    classic: true

- name: Create a directory kube
  ansible.builtin.file:
    path: /home/sparrow/.kube
    state: directory

- name: Copy admin file
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/sparrow/.kube/config
    remote_src: yes
    mode: '0777'

- name: Deploy cert-manager
  ansible.builtin.shell:
    cmd: kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.yaml

- name: Copy wp-config
  ansible.builtin.copy:
      src: wp-config.php
      dest: wp-config.php
      backup: yes

- name: Verify Permissions on wp-config
  ansible.builtin.file:
    path: wp-config.php
    mode: '0777'

- name: Copy helm chart
  ansible.builtin.copy:
      src: wordpress/
      dest: wordpress/

- name: Verify Permissions on wordpress/
  ansible.builtin.file:
    path: wordpress/
    mode: '0777'

- name: Deploy
  kubernetes.core.helm:
    name: wordpress
    chart_ref: wordpress/
    release_namespace: default
