apiVersion: batch/v1
kind: CronJob
metadata:
  name: nginx-cronjob
  namespace: globallogic
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl
            command: ['curl 10.107.233.173']
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3

