apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
{{ include "nginxchart.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "nginxchart.labels" . | indent 6 }}            
  template:
    metadata:
      labels:
{{ include "nginxchart.labels" . | indent 8 }}
    spec:
      containers:
      - name: {{ .Release.Name }}-container
        image: {{ .Values.container.image }}
        ports:
        - containerPort: {{ .Values.container.port }}
          name: {{ .Release.Name }}-http
