apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
{{ include "nginxchart.labels" . | indent 4 }}
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: {{ .Release.Name }}-http
